nuscenes:
  dataroot: "/Users/rohithkumarballem/Downloads/nuscenes"   # adjust if different
  version: "v1.0-mini"
  cameras: ["CAM_FRONT","CAM_FRONT_LEFT","CAM_FRONT_RIGHT","CAM_BACK","CAM_BACK_LEFT","CAM_BACK_RIGHT"]
  lidar: "LIDAR_TOP"
  image_size: [224, 384]   # small to limit tokens on MPS
